### ISSUE TITLE
MongoDB connection errors

### ISSUE THREAD

**Issue by nmn** [gordonmleigh/promised-mongo#11]
I've getting these errors very often of late.

```
Error: failed to connect to [mongo.onmodulus.net:27017]
      at null.<anonymous> (/mnt/data/1/node_modules/promised-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
      at EventEmitter.emit (events.js:118:17)
      at null.<anonymous> (/mnt/data/1/node_modules/promised-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
      at EventEmitter.emit (events.js:110:17)
      at Socket.<anonymous> (/mnt/data/1/node_modules/promised-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
      at Socket.EventEmitter.emit (events.js:107:17)
      at net.js:436:14
      at process._tickCallback (node.js:343:11)
```

Also, there have been no new commits to promised-mongo of late. Mongojs has continued to update. In Promised mongo still under development?

**Comment by gordonmleigh** [comment]
I think that's your server refusing connections.  Sorry for the delays in development.
