### ISSUE TITLE
Can't close the database

### ISSUE THREAD

**Issue by DenisGorbachev** [gordonmleigh/promised-mongo#31]
A `mongodb.close()` call throws the following error:

```
Unhandled rejection TypeError: undefined is not a function
  at Database.close$ (/var/www/swf/core/node_modules/promised-mongo/dist/Database.js:132:30)
  at tryCatch (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/regenerator/runtime.js:67:40)
  at GeneratorFunctionPrototype.invoke [as _invoke] (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/regenerator/runtime.js:315:22)
  at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/regenerator/runtime.js:100:21)
  at GeneratorFunctionPrototype.invoke (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  at run (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
  at /var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
  at flush (/var/www/swf/core/node_modules/promised-mongo/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by DenisGorbachev** [comment]
@gordonmleigh could you please take a look? This issue actually manifests in production...

**Comment by IvanDimanov** [comment]
@gordonmleigh I can confirm the error on my system as well.

```
$ npm version
{ npm: '2.14.7',
  icu: '52.1',
  node: '4.2.2',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35' }
```

**Comment by Foosvald** [comment]
We get almost the same stack trace as @DenisGorbachev, with the only difference that the first line is different:

```
 TypeError: context$2$0.sent.destroy is not a function
    at Database.close$ (/var/lib/jenkins/jobs/apollo-web-services/jobs/Master/workspace/node_modules/besedo-mongo/node_modules/promised-mongo/dist/Database.js:132:30)
```

We're running Node 4.2.2 and Mongodb 3.0.7.

**Comment by ralyodio** [comment]
my script just hangs. I assume its because i don't disconnect from DB?
