### ISSUE TITLE
Cursor.toArray() fails for large number of records

### ISSUE THREAD

**Issue by yangchristian** [gordonmleigh/promised-mongo#39]
For a large number of records (600 to be exact, not sure why that is the magic number), `toArray()` fails and throws a `Recursive process.nextTick detected` error for each record (full stack trace at bottom).

We were able to create a minimal repro by adding a test similar to the `toArray` test, just with more records (also available in our [fork branch](https://github.com/CrossLead/promised-mongo/commit/be459bc858667a3d6df78266bb6ab59ba85b9c52)):

``` js
    it('should be able to handle lots of documents', async function () {
      const docsToInsert = [], numDocs = 600;
      for (let i = 0; i < numDocs; i++) {
        docsToInsert[i] = {
          i,
          name: `Pokemon ID #${i}`
        };
      }
      await collection.insert(docsToInsert);

      let result = await collection.find().toArray();

      expect(result).to.be.an.instanceof(Array);
      expect(result.length).to.equal(numDocs);
    });
```

I suspect this has to do with the `async` `while` loop, however, I am unable to get the error to repro with a minimal [Babel REPL](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=const%20limit%20%3D%20800%3B%0Alet%20i%20%3D%200%3B%0A%0Afunction%20cb%28fn%29%20%7B%0A%20%20fn%28%2B%2Bi%20%3E%20limit%20%3F%200%20%3A%20i%29%3B%0A%7D%3B%0A%0Aasync%20function%20next%28%29%20%7B%0A%20%20return%20await%20new%20Promise%28function%28resolve%2Creject%29%20%7B%0A%20%20%20%20cb%28result%20%3D%3E%20%7B%0A%20%20%20%20%20%20resolve%28result%29%0A%20%20%20%20%7D%29%3B%0A%20%20%7D%29%3B%0A%7D%0A%0Aasync%20function%20nextLoop%28%29%20%7B%0A%20%20const%20result%20%3D%20%5B%5D%3B%0A%20%20let%20num%20%3D%20null%3B%0A%20%20%0A%20%20while%20%28num%20%3D%20await%20next%28%29%29%20%7B%0A%20%20%20%20result.push%28num%29%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20result%3B%0A%7D%0A%0AnextLoop%28%29.then%28arr%20%3D%3E%20%7B%0A%20%20console.log%28arr.length%29%3B%0A%7D%29%3B), even with a high result count.

Here is the stack trace for **each** loop iteration:

``` js
Trace: (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Console.warn (console.js:62:16)
    at Console.trace (console.js:122:8)
    at maxTickWarn (node.js:410:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at Object.exports.cursor.deleteLine (C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\reporters\base.js:137:30)
    at Object.exports.cursor.CR (C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\reporters\base.js:146:22)
    at Runner.<anonymous> (C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\reporters\spec.js:67:14)
    at Runner.emit (events.js:117:20)
    at C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\runner.js:547:14
    at done (C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\runnable.js:247:5)
    at C:\Users\C\AppData\Roaming\nvm\v0.10.38\node_modules\mocha\lib\runnable.js:291:11
    at run (C:\htdocs\promised-mongo\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\es6.promise.js:89:39)
    at C:\htdocs\promised-mongo\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\es6.promise.js:100:28
    at flush (C:\htdocs\promised-mongo\node_modules\babel\node_modules\babel-core\node_modules\core-js\modules\$.microtask.js:17:13)
    at process._tickCallback (node.js:448:13)
```

**Comment by yangchristian** [comment]
(also note this used to work in v0.11, which is how we found out about the issue in the first place)
