### ISSUE TITLE
TypeError: Cannot read property '_serverPromise' of undefined

### ISSUE THREAD

**Issue by ralyodio** [gordonmleigh/promised-mongo#56]
Getting this error. not sure from where.

	TypeError: Cannot read property '_serverPromise' of undefined
	    at close$ (/Users//home/user/test/node_modules/promised-mongo/dist/Database.js:123:22)
	    at tryCatch (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:72:40)
	    at Generator.invoke [as _invoke] (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:334:22)
	    at Generator.prototype.(anonymous function) [as next] (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:105:21)
	    at tryCatch (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:72:40)
	    at invoke (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:146:20)
	    at /Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:191:11
	    at F (/Users//home/user/test/node_modules/core-js/library/modules/$.export.js:30:36)
	    at callInvokeWithMethodAndArg (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:190:16)
	    at AsyncIterator.enqueue [as _invoke] (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:211:37)
	    at AsyncIterator.prototype.(anonymous function) [as next] (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:105:21)
	    at Object.runtime.async (/Users//home/user/test/node_modules/babel-runtime/regenerator/runtime.js:228:12)
	    at close (/Users//home/user/test/node_modules/promised-mongo/dist/Database.js:118:34)

**Comment by ralyodio** [comment]
My bad. had to bind to `.then(this.db.close.bind(this.db))` in my promise callback
