### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string.

### ISSUE THREAD

**Issue by vineetasharma** [gordonmleigh/promised-mongo#57]
Error log:
```
/home/ttnd/GraphQL/graphql-blog-schema/node_modules/promised-mongo/dist/Collection.js:77
    this.fullCollectionName = db.config.dbName + '.' + collectionName;
                                                     ^

TypeError: Cannot convert a Symbol value to a string
    at new Collection (/home/ttnd/GraphQL/graphql-blog-schema/node_modules/promised-mongo/dist/Collection.js:77:54)
    at Database.collection (/home/ttnd/GraphQL/graphql-blog-schema/node_modules/promised-mongo/dist/Database.js:146:14)
    at Object.ES2015Proxy.get (/home/ttnd/GraphQL/graphql-blog-schema/node_modules/promised-mongo/index.js:31:44)
    at Object.objectToString (internal/util.js:84:36)
    at isError (internal/util.js:80:18)
    at formatValue (util.js:535:7)
    at inspect (util.js:198:10)
    at exports.format (util.js:133:20)
    at Console.log (console.js:43:37)
    at Object.<anonymous> (/home/ttnd/GraphQL/graphql-blog-schema/Promise_Test.js:21:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```
Code:
```
const mongo = require('promised-mongo');
const db = mongo("mongodb://localhost:27017/myNewDB", ["authors"]);
const authorsCollection = db.collection('authors');
console.log('authorsVollection-------------------',db);
```
Getting above error if prints the  db in console.log.

**Comment by ashleydavis** [comment]
This issue happens with node version 6 and 7.

**Comment by sairamdevarashetty** [comment]
+1

**Comment by laurynas-karvelis** [comment]
It happens with node v. 8 and 9 too
